// <auto-generated />
using System;
using FamilyHubs.ServiceDirectory.Infrastructure.Persistence.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace fhservicedirectoryapi.api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230203185402_FixFkIssues")]
    partial class FixFkIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.AccessibilityForDisabilities", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Accessibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accessibility");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locationid");

                    b.HasKey("Id")
                        .HasName("pk_accessibilityfordisabilities");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_accessibilityfordisabilities_locationid");

                    b.ToTable("accessibilityfordisabilities", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.AdminArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organisationid");

                    b.HasKey("Id")
                        .HasName("pk_adminareas");

                    b.ToTable("adminareas", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telephone");

                    b.Property<string>("TextPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("textphone");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.CostOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("AmountDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("amountdescription");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LinkId")
                        .HasColumnType("text")
                        .HasColumnName("linkid");

                    b.Property<string>("Option")
                        .HasColumnType("text")
                        .HasColumnName("option");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validto");

                    b.HasKey("Id")
                        .HasName("pk_costoptions");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_costoptions_serviceid");

                    b.ToTable("costoptions", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Eligibility", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("EligibilityDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eligibilitydescription");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LinkId")
                        .HasColumnType("text")
                        .HasColumnName("linkid");

                    b.Property<int>("MaximumAge")
                        .HasColumnType("integer")
                        .HasColumnName("maximumage");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("integer")
                        .HasColumnName("minimumage");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.HasKey("Id")
                        .HasName("pk_eligibilities");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_eligibilities_serviceid");

                    b.ToTable("eligibilities", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Funding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_fundings");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_fundings_serviceid");

                    b.ToTable("fundings", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.HolidaySchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closesat");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enddate");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<DateTime?>("OpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opensat");

                    b.Property<string>("ServiceAtLocationId")
                        .HasColumnType("text")
                        .HasColumnName("serviceatlocationid");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.HasKey("Id")
                        .HasName("pk_holidayschedules");

                    b.HasIndex("ServiceAtLocationId")
                        .HasDatabaseName("ix_holidayschedules_serviceatlocationid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_holidayschedules_serviceid");

                    b.ToTable("holidayschedules", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_languages_serviceid");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.LinkContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ContactId")
                        .HasColumnType("text")
                        .HasColumnName("contactid");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LinkId")
                        .HasColumnType("text")
                        .HasColumnName("linkid");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("linktype");

                    b.HasKey("Id")
                        .HasName("pk_linkcontacts");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_linkcontacts_contactid");

                    b.HasIndex("LinkId")
                        .HasDatabaseName("ix_linkcontacts_linkid");

                    b.ToTable("linkcontacts", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.LinkTaxonomy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LinkId")
                        .HasColumnType("text")
                        .HasColumnName("linkid");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("linktype");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parentid");

                    b.Property<string>("TaxonomyId")
                        .HasColumnType("text")
                        .HasColumnName("taxonomyid");

                    b.HasKey("Id")
                        .HasName("pk_linktaxonomies");

                    b.HasIndex("LinkId")
                        .HasDatabaseName("ix_linktaxonomies_linkid");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_linktaxonomies_parentid");

                    b.HasIndex("TaxonomyId")
                        .HasDatabaseName("ix_linktaxonomies_taxonomyid");

                    b.ToTable("linktaxonomies", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrganisationTypeId")
                        .HasColumnType("text")
                        .HasColumnName("organisationtypeid");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("OrganisationTypeId")
                        .HasDatabaseName("ix_organisations_organisationtypeid");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.OrganisationType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organisationtypes");

                    b.ToTable("organisationtypes", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Parent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Vocabulary")
                        .HasColumnType("text")
                        .HasColumnName("vocabulary");

                    b.HasKey("Id")
                        .HasName("pk_parents");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.PhysicalAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address1");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locationid");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("postcode");

                    b.Property<string>("StateProvince")
                        .HasColumnType("text")
                        .HasColumnName("stateprovince");

                    b.HasKey("Id")
                        .HasName("pk_physicaladdresses");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_physicaladdresses_locationid");

                    b.ToTable("physicaladdresses", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.RegularSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ByDay")
                        .HasColumnType("text")
                        .HasColumnName("byday");

                    b.Property<string>("ByMonthDay")
                        .HasColumnType("text")
                        .HasColumnName("bymonthday");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closesat");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DtStart")
                        .HasColumnType("text")
                        .HasColumnName("dtstart");

                    b.Property<string>("Freq")
                        .HasColumnType("text")
                        .HasColumnName("freq");

                    b.Property<string>("Interval")
                        .HasColumnType("text")
                        .HasColumnName("interval");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<DateTime?>("OpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opensat");

                    b.Property<string>("ServiceAtLocationId")
                        .HasColumnType("text")
                        .HasColumnName("serviceatlocationid");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validto");

                    b.HasKey("Id")
                        .HasName("pk_regularschedules");

                    b.HasIndex("ServiceAtLocationId")
                        .HasDatabaseName("ix_regularschedules_serviceatlocationid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_regularschedules_serviceid");

                    b.ToTable("regularschedules", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.RelatedOrganisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organisationid");

                    b.Property<string>("RelatedOrganisationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relatedorganisationid");

                    b.HasKey("Id")
                        .HasName("pk_relatedorganisations");

                    b.ToTable("relatedorganisations", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("OrganisationId")
                        .HasColumnType("text")
                        .HasColumnName("organisationid");

                    b.Property<string>("Score")
                        .HasColumnType("text")
                        .HasColumnName("score");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Widget")
                        .HasColumnType("text")
                        .HasColumnName("widget");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_reviews_organisationid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_reviews_serviceid");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Accreditations")
                        .HasColumnType("text")
                        .HasColumnName("accreditations");

                    b.Property<DateTime?>("AssuredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assureddate");

                    b.Property<string>("AttendingAccess")
                        .HasColumnType("text")
                        .HasColumnName("attendingaccess");

                    b.Property<string>("AttendingType")
                        .HasColumnType("text")
                        .HasColumnName("attendingtype");

                    b.Property<bool>("CanFamilyChooseDeliveryLocation")
                        .HasColumnType("boolean")
                        .HasColumnName("canfamilychoosedeliverylocation");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("DeliverableType")
                        .HasColumnType("text")
                        .HasColumnName("deliverabletype");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Fees")
                        .HasColumnType("text")
                        .HasColumnName("fees");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organisationid");

                    b.Property<string>("ServiceTypeId")
                        .HasColumnType("text")
                        .HasColumnName("servicetypeid");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_services_organisationid");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_services_servicetypeid");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("Extent")
                        .HasColumnType("text")
                        .HasColumnName("extent");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LinkId")
                        .HasColumnType("text")
                        .HasColumnName("linkid");

                    b.Property<string>("ServiceAreaDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceareadescription");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_serviceareas");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_serviceareas_serviceid");

                    b.ToTable("serviceareas", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceAtLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locationid");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.HasKey("Id")
                        .HasName("pk_serviceatlocations");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_serviceatlocations_locationid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_serviceatlocations_serviceid");

                    b.ToTable("serviceatlocations", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceDelivery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.HasKey("Id")
                        .HasName("pk_servicedeliveries");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_servicedeliveries_serviceid");

                    b.ToTable("servicedeliveries", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceTaxonomy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("LinkId")
                        .HasColumnType("text")
                        .HasColumnName("linkid");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parentid");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serviceid");

                    b.Property<string>("TaxonomyId")
                        .HasColumnType("text")
                        .HasColumnName("taxonomyid");

                    b.HasKey("Id")
                        .HasName("pk_servicetaxonomies");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_servicetaxonomies_parentid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_servicetaxonomies_serviceid");

                    b.HasIndex("TaxonomyId")
                        .HasDatabaseName("ix_servicetaxonomies_taxonomyid");

                    b.ToTable("servicetaxonomies", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_servicetypes");

                    b.ToTable("servicetypes", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Taxonomy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<string>("EligibilityId")
                        .HasColumnType("text")
                        .HasColumnName("eligibilityid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Parent")
                        .HasColumnType("text")
                        .HasColumnName("parent");

                    b.Property<string>("Vocabulary")
                        .HasColumnType("text")
                        .HasColumnName("vocabulary");

                    b.HasKey("Id")
                        .HasName("pk_taxonomies");

                    b.HasIndex("EligibilityId")
                        .HasDatabaseName("ix_taxonomies_eligibilityid");

                    b.ToTable("taxonomies", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.UiCache", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("lastmodifiedby");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_uicaches");

                    b.ToTable("uicaches", (string)null);
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.AccessibilityForDisabilities", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Location", null)
                        .WithMany("AccessibilityForDisabilities")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accessibilityfordisabilities_locations_locationid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.CostOption", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("CostOptions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_costoptions_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Eligibility", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("Eligibilities")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eligibilities_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Funding", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("Fundings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fundings_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.HolidaySchedule", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.ServiceAtLocation", null)
                        .WithMany("HolidaySchedules")
                        .HasForeignKey("ServiceAtLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_holidayschedules_serviceatlocations_serviceatlocationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("HolidaySchedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_holidayschedules_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Language", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("Languages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_languages_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.LinkContact", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .HasConstraintName("fk_linkcontacts_contacts_contactid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Location", null)
                        .WithMany("LinkContacts")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_linkcontacts_locations_locationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Organisation", null)
                        .WithMany("LinkContacts")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_linkcontacts_organisations_organisationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("LinkContacts")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_linkcontacts_services_serviceid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.ServiceAtLocation", null)
                        .WithMany("LinkContacts")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_linkcontacts_serviceatlocations_serviceatlocationid");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.LinkTaxonomy", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Location", null)
                        .WithMany("LinkTaxonomies")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_linktaxonomies_locations_locationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Parent", null)
                        .WithMany("LinkTaxonomies")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_linktaxonomies_parents_parentid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Taxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxonomyId")
                        .HasConstraintName("fk_linktaxonomies_taxonomies_taxonomyid");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Organisation", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.OrganisationType", "OrganisationType")
                        .WithMany()
                        .HasForeignKey("OrganisationTypeId")
                        .HasConstraintName("fk_organisations_organisationtypes_organisationtypeid");

                    b.Navigation("OrganisationType");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.PhysicalAddress", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Location", null)
                        .WithMany("PhysicalAddresses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_physicaladdresses_locations_locationid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.RegularSchedule", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.ServiceAtLocation", null)
                        .WithMany("RegularSchedules")
                        .HasForeignKey("ServiceAtLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_regularschedules_serviceatlocations_serviceatlocationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("RegularSchedules")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_regularschedules_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Review", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Organisation", null)
                        .WithMany("Reviews")
                        .HasForeignKey("OrganisationId")
                        .HasConstraintName("fk_reviews_organisations_organisationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Service", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Organisation", null)
                        .WithMany("Services")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_organisations_organisationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .HasConstraintName("fk_services_servicetypes_servicetypeid");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceArea", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("ServiceAreas")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_serviceareas_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceAtLocation", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_serviceatlocations_locations_locationid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("ServiceAtLocations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_serviceatlocations_services_serviceid");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceDelivery", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("ServiceDeliveries")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicedeliveries_services_serviceid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceTaxonomy", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Parent", null)
                        .WithMany("ServiceTaxonomies")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_servicetaxonomies_parents_parentid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Service", null)
                        .WithMany("ServiceTaxonomies")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicetaxonomies_services_serviceid");

                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Taxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxonomyId")
                        .HasConstraintName("fk_servicetaxonomies_taxonomies_taxonomyid");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Taxonomy", b =>
                {
                    b.HasOne("FamilyHubs.ServiceDirectory.Core.Entities.Eligibility", null)
                        .WithMany("Taxonomies")
                        .HasForeignKey("EligibilityId")
                        .HasConstraintName("fk_taxonomies_eligibilities_eligibilityid");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Eligibility", b =>
                {
                    b.Navigation("Taxonomies");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Location", b =>
                {
                    b.Navigation("AccessibilityForDisabilities");

                    b.Navigation("LinkContacts");

                    b.Navigation("LinkTaxonomies");

                    b.Navigation("PhysicalAddresses");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Organisation", b =>
                {
                    b.Navigation("LinkContacts");

                    b.Navigation("Reviews");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Parent", b =>
                {
                    b.Navigation("LinkTaxonomies");

                    b.Navigation("ServiceTaxonomies");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.Service", b =>
                {
                    b.Navigation("CostOptions");

                    b.Navigation("Eligibilities");

                    b.Navigation("Fundings");

                    b.Navigation("HolidaySchedules");

                    b.Navigation("Languages");

                    b.Navigation("LinkContacts");

                    b.Navigation("RegularSchedules");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceAreas");

                    b.Navigation("ServiceAtLocations");

                    b.Navigation("ServiceDeliveries");

                    b.Navigation("ServiceTaxonomies");
                });

            modelBuilder.Entity("FamilyHubs.ServiceDirectory.Core.Entities.ServiceAtLocation", b =>
                {
                    b.Navigation("HolidaySchedules");

                    b.Navigation("LinkContacts");

                    b.Navigation("RegularSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
